name: Publish Vue Site to GitHub Pages

on:
  push:
    branches: [ "main" ]

env:
  VUEDIR: vue-project

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 24

    - name: Install Dependencies
      run: cd ${{ env.VUEDIR }} && npm install

    - name: Build Site
      run: cd ${{ env.VUEDIR }} && npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ env.VUEDIR }}/dist
        force_orphan: true